name: Build and Push Images

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build ${{ matrix.service }} image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: api
            context: api
            dockerfile: api/Dockerfile
            image: open-elo-api
          - service: client
            context: client
            dockerfile: client/Dockerfile
            image: open-elo-client

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        id: prep
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
          echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/${{ matrix.image }}" >> $GITHUB_ENV
          echo "VERSION_SHA=sha-${GITHUB_SHA}" >> $GITHUB_ENV
          echo "TAGS=${{ env.IMAGE }}:latest,${{ env.IMAGE }}:${GITHUB_SHA}" >> $GITHUB_ENV || true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.OWNER_LC }}/${{ matrix.image }}
          tags: |
            type=raw,value=latest
            type=raw,value=sha-${{ github.sha }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Summary
        run: |
          echo "Pushed: ${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
